<a href="https://colab.research.google.com/github/captmmari/Moringa-wk3/blob/main/Copy_of_Moringa_Data_Science_Prep_W2_Independent_Project_2021_09_Simon_Mmari_Python_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Independent Project

# 1.0 Importing our Libraries

In [21]:
# Importing the pandas library
import pandas as pd

# Import the numpy library
import numpy as np

# 1.1 Loading the Datasets

In [22]:
# Uploading the Autolib_dataset
df = pd.read_csv('/content/Autolib_dataset (2).csv')
df

                                 Address  Cars  ...  hour  minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                 8 avenue MÃ©nelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 25 columns]

In [23]:
# First ten rows
df.head(10)

                              Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue EugÃ¨ne OudinÃ©     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23
5                8 Boulevard Voltaire     0                0  ...    6     7       2
6                      37 rue Leblanc     0                0  ...    8    18      20
7         17 Rue des Luaps ProlongÃ©e     3                3  ...    4    22      13
8               34 avenue Jean Moulin     1                1  ...    2    22      58
9        41 boulevard de Rochechouart     6                6  ...    4    15       2

[10 rows x 25 columns]

In [24]:
# Obtain information about the Autolib_dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64
 2   Bluecar counter      5000 non-null   int64
 3   Utilib counter       5000 non-null   int64
 4   Utilib 1.4 counter   5000 non-null   int64
 5   Charge Slots         5000 non-null   int64
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots                5000 non-null   int64
 17  Station type         5000 non-null   object
 18  Status               5000 non-null   object
 19  Subscription status  5000 non-null   object
 20  year                 5000 non-null   int64
 21  month                5000 non-null   int64
 22  day                  5000 non-null   int64
 23  hour                 5000 non-null   int64
 24  minute               5000 non-null   int64
dtypes: int64(12), object(13)
memory usage: 976.7+ KB

In [25]:
# Checking for nulls

df.isnull().sum()

Address                   0
Cars                      0
Bluecar counter           0
Utilib counter            0
Utilib 1.4 counter        0
Charge Slots              0
Charging Status           0
City                      0
Displayed comment      4889
ID                        0
Kind                      0
Geo point                 0
Postal code               0
Public name               0
Rental status             0
Scheduled at           4953
Slots                     0
Station type              0
Status                    0
Subscription status       0
year                      0
month                     0
day                       0
hour                      0
minute                    0
dtype: int64

In [26]:
# Drop the nulls
df.dropna().sum()

Address                0.0
Cars                   0.0
Bluecar counter        0.0
Utilib counter         0.0
Utilib 1.4 counter     0.0
Charge Slots           0.0
Charging Status        0.0
City                   0.0
Displayed comment      0.0
ID                     0.0
Kind                   0.0
Geo point              0.0
Postal code            0.0
Public name            0.0
Rental status          0.0
Scheduled at           0.0
Slots                  0.0
Station type           0.0
Status                 0.0
Subscription status    0.0
year                   0.0
month                  0.0
day                    0.0
hour                   0.0
minute                 0.0
dtype: float64

In [27]:
# dropping unnecessary Columns

df.drop(["Displayed comment", "Scheduled at", "year",], axis = 1,inplace = True)
df

                                 Address  Cars  ...  hour  minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                 8 avenue MÃ©nelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 22 columns]

In [28]:
# Checking if there is any missing value in dataframe as a whole
df = pd.DataFrame(df,columns=['Address', 'Cars',	'Bluecar counter',	'Utilib counter',	'Utilib 1.4 counter',	'Charge Slots',	'Charging Status',	'City',	'ID',	'Kind',	'Geo point',	'Postal code',	'Public name',	'Rental status',	'Slots',	'Station type',	'Status',	'Subscription status', 'hour'])
df

                                 Address  Cars  ...  Subscription status  hour
0                    2 Avenue de Suffren     0  ...          nonexistent    11
1              145 Rue Raymond Losserand     6  ...          nonexistent     7
2       2 Avenue John Fitzgerald Kennedy     3  ...          nonexistent    20
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...          nonexistent     4
4     6 avenue de la Porte de Champerret     3  ...          nonexistent    17
...                                  ...   ...  ...                  ...   ...
4995                 8 avenue MÃ©nelotte     2  ...          nonexistent    11
4996                   37 rue de Dantzig     4  ...          nonexistent    16
4997                      142 rue du Bac     1  ...          nonexistent     7
4998         2 avenue du Val de Fontenay     2  ...          nonexistent    17
4999                 5 Rue Henry Brisson     4  ...          nonexistent    10

[5000 rows x 19 columns]

In [29]:
# Dropping missing values
df = df.dropna()
df

                                 Address  Cars  ...  Subscription status  hour
0                    2 Avenue de Suffren     0  ...          nonexistent    11
1              145 Rue Raymond Losserand     6  ...          nonexistent     7
2       2 Avenue John Fitzgerald Kennedy     3  ...          nonexistent    20
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...          nonexistent     4
4     6 avenue de la Porte de Champerret     3  ...          nonexistent    17
...                                  ...   ...  ...                  ...   ...
4995                 8 avenue MÃ©nelotte     2  ...          nonexistent    11
4996                   37 rue de Dantzig     4  ...          nonexistent    16
4997                      142 rue du Bac     1  ...          nonexistent     7
4998         2 avenue du Val de Fontenay     2  ...          nonexistent    17
4999                 5 Rue Henry Brisson     4  ...          nonexistent    10

[5000 rows x 19 columns]

In [30]:
# Dropping all NA values
all_rows_any_na = df.dropna()
all_rows_any_na

                                 Address  Cars  ...  Subscription status  hour
0                    2 Avenue de Suffren     0  ...          nonexistent    11
1              145 Rue Raymond Losserand     6  ...          nonexistent     7
2       2 Avenue John Fitzgerald Kennedy     3  ...          nonexistent    20
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...          nonexistent     4
4     6 avenue de la Porte de Champerret     3  ...          nonexistent    17
...                                  ...   ...  ...                  ...   ...
4995                 8 avenue MÃ©nelotte     2  ...          nonexistent    11
4996                   37 rue de Dantzig     4  ...          nonexistent    16
4997                      142 rue du Bac     1  ...          nonexistent     7
4998         2 avenue du Val de Fontenay     2  ...          nonexistent    17
4999                 5 Rue Henry Brisson     4  ...          nonexistent    10

[5000 rows x 19 columns]

In [31]:
# Changing Columns ta upper cases
df = df.columns.str.strip().str.upper().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
print(df)

Index(['ADDRESS', 'CARS', 'BLUECAR_COUNTER', 'UTILIB_COUNTER',
       'UTILIB_1.4_COUNTER', 'CHARGE_SLOTS', 'CHARGING_STATUS', 'CITY', 'ID',
       'KIND', 'GEO_POINT', 'POSTAL_CODE', 'PUBLIC_NAME', 'RENTAL_STATUS',
       'SLOTS', 'STATION_TYPE', 'STATUS', 'SUBSCRIPTION_STATUS', 'HOUR'],
      dtype='object')

# Expoting Analysed dataset

# 1.2 Question

In [17]:
# Identify the most popular hour of the day for picking up a shared electric car (Bluecar)
# in the city of Paris over the month of April 2018.

#df = df[df['BLUECAR COUNTER'] == 'HOUR']
#df
#b=df.iloc[3:0].sum().sort_values(ascending=False)
#b.loc[b==b.max()]

maxValue = df['HOUR'].max()
print("Maximum value in column 'HOUR': " , maxValue)

IndexError: ignored

In [37]:
# What station is the most popular?
df = pd.read_csv(Columns = 'station'.groupby.sum().sort_values(ascending+False).head(1))

AttributeError: ignored